title: My Resume
profile_img: /assets/img/profile-avatar.jpg
icon_img: /assets/img/icon.webp

name: Vo Ho Anh Tuan
job: Software Engineer

phone_number: +84 913-938-881
address: Binh Tan, Ho Chi Minh
email: hoanhtuan.vo@gmail.com
linkedin_username: www.linkedin.com/in/ho-anh-tuan-vo
github_username: https://github.com/VoHoAnhTuan
instagram_username: https://instagram.com
twitter_username: https://x.com
facebook_username: https://facebook.com
youtube_username: https://youtube.com
blog_url: Home

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag